accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:post_id>/", views.view, name="view"),
    path("post/", views.post, name="post"),
    path("create/", views.create_post, name="create_post"),
]

cyberblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Post(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(default="Post title", max_length=255)
    text = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import (
    authenticate,
    login as django_login,
    logout as django_logout,
)


@csrf_exempt
@xframe_options_exempt
def register(request):
    context = {}
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password").lower()
        password2 = request.POST.get("password2").lower()
        if password2 == password:
            if len(password) <= 8 and password.isalnum():
                if (
                    len(username) <= 20
                    and username.isalnum()
                    and not User.objects.filter(username=username).exists()
                ):
                    user = User.objects.create_superuser(username, None, password)
                    django_login(request, user)
                    return redirect("/")
                else:
                    context["invalid_username"] = True
            else:
                context["invalid_password"] = True
        else:
            context["no_match"] = True

    return render(request, "accounts/register.html", context)


@csrf_exempt
@xframe_options_exempt
def login(request):
    context = {"next": request.GET.get("next", "/")}
    if request.method == "POST":
        context["next"] = request.POST.get("next", context.get("next", "/"))
        username = request.POST.get("username")
        password = request.POST.get("password").lower()
        user = authenticate(request, username=username, password=password)
        if user:
            django_login(request, user)
            return redirect(context["next"])
        else:
            context["invalid"] = True

    return render(request, "accounts/login.html", context)


def logout(request):
    django_logout(request)
    return redirect("/")

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.clickjacking import xframe_options_exempt
import datetime

from .models import Post


@xframe_options_exempt
def index(request):
    latest_posts = Post.objects.order_by("-date")[:100]
    return render(request, "blog/index.html", context={"latest_posts": latest_posts})


@xframe_options_exempt
def view(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "blog/view.html", {"post": post})


def text2paras(text):
    output_paras = []
    output = ""

    for line in text.splitlines():
        if line.strip():
            if output:
                output += "<br />"
            output += line
        else:
            if output:
                output_paras.append(output)
                output = ""

    output_paras.append(output)
    return "".join("<p>" + para + "</p>" for para in output_paras)


@login_required
@csrf_exempt
@xframe_options_exempt
def create_post(request):
    post = Post()
    post.author = request.user
    post.title = request.GET.get("title", "No title")
    post.text = text2paras(request.GET.get("text", ""))
    post.date = datetime.datetime.now()
    post.save()
    return redirect("/blog/")


@login_required
@csrf_exempt
@xframe_options_exempt
def post(request):
    return render(request, "blog/post.html")

cyberblog/views.py
from django.shortcuts import render


def index(request):
    return render(request, "cyberblog/index.html")

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Log in</title>
  </head>
  <body>
    <form method="POST" action="{% url "accounts:login" %}">
      {% csrf_token %}
      <label for="username">Username:</label><br />
      <input type="text" id="username" name="username" /><br />
      <label for="text">Password:</label><br />
      <input type="password" id="password" name="password" /><br />
      <input type="hidden" id="next" name="next" value="{{ next }}" />
      <input type="submit" value="Log in">
    </form>
    {% if invalid %}
    <p>Login failed. Try again.</p>
    {% endif %}
  </body>
</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sign up</title>
  </head>
  <body>
    <form method="POST" action="{% url "accounts:register" %}">
      {% csrf_token %}
      <label for="username">Username:</label><br />
      <input type="text" id="username" name="username" /><br />
      <label for="text">Password:</label><br />
      <input type="password" id="password" name="password" /><br />
      <label for="text">Re-enter password:</label><br />
      <input type="password" id="password2" name="password2" /><br />
      <input type="submit" value="Register">
    </form>
    {% if no_match %}
    <p>Passwords do not match. Try again.</p>
    {% elif invalid_username %}
    <p>Username is not available. Try again.</p>
    {% elif invalid_password %}
    <p>Password should be 8 or fewer characters and cannot contain special characters. Try again.</p>
    {% endif %}
  </body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
  </head>
  <body>
    <p><a href="{% url "index" %}">To front page</a></p>
    {% if latest_posts %}
      <ul>
      {% for post in latest_posts %}
        <li><a href="{% url "blog:view" post.id %}">{{ post.date }} - {{ post.title }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No posts.</p>
    {% endif %}
  </body>
</html>

blog/templates/blog/post.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New blog post</title>
  </head>
  <body>
    <form method="GET" action="{% url "blog:create_post" %}">
      <label for="title">Post title:</label><br />
      <input type="text" id="title" name="title" value="Post title" /><br />
      <label for="text">Post text:</label><br />
      <textarea id="text" name="text" style="height: 200px; width: 400px"></textarea><br />
      <input type="submit" value="Submit">
    </form>
    <p><a href="{% url "index" %}">Go back</a></p>
  </body>
</html>

blog/templates/blog/view.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ post.title }}</title>
  </head>
  <body>
    <p><a href="{% url "blog:index" %}">Back to index</a></p>
    <h1>{{ post.title }}</h1>
    <p>By {{ post.author }} on {{ post.date }}</p>
    {{ post.text|safe }}
  </body>
</html>

cyberblog/templates/cyberblog/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Cyber Blog Site</title>
  </head>
  <body>
    <p>Welcome to cyber security blog site</p>
    {% if user.is_authenticated %}
    <p>You're logged in as {{ user.get_username }}</p>
    <p><a href="{% url "accounts:logout" %}">Log out</a></p>
    <p><a href="{% url "blog:post" %}">Create new post</a></p>
    {% else %}
    <p><a href="{% url "accounts:login" %}">Log in</a></p>
    <p><a href="{% url "accounts:register" %}">Sign up</a></p>
    {% endif %}
    <p><a href="{% url "blog:index" %}">View all posts</a></p>
  </body>
</html>